#spring.application.name=station-service
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/stationServiceDb
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
