server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentServiceDb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  charging-service:
    url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info