server:
  port: 8084

spring:
  application:
    name: charging-service

  datasource:
    url: jdbc:postgresql://localhost:5432/chargingServiceDb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  booking-service:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info


  kafka:
    bootstrap-servers: localhost:9092

